services:
  prom-pushgateway:
    image: prom/pushgateway
    ports:
      - 9091:9091
    networks:
      - mgmt_network

  prometheus:
    image: prom/prometheus
    volumes:
      - ./monitoring/prometheus:/etc/prometheus:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - 9090:9090
    networks:
      - mgmt_network

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./monitoring/grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=infrahub
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=aceiot-svg-panel
    networks:
      - mgmt_network

networks:
  mgmt_network:
    external: true
